version: '3.8'

services:
  smart-repo-assistant:
    build: .
    ports:
      - "5000:5000"
      - "8501:8501"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}
      - DEFAULT_REPO=${DEFAULT_REPO}
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
    volumes:
      - ./logs:/app/logs
      - ./reports:/app/reports
    restart: unless-stopped

  # Optional: Add a reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - smart-repo-assistant
    restart: unless-stopped